### ISSUE TITLE
Paths for system and image prompts

### ISSUE THREAD

**Issue by jobreu** [frankiethull/kuzco#1]
Thx for this cool package! When I wanted to try it out, I got an error message (apologies for it being in German) when I ran the example code from the ReadMe.

Code:

```
library(kuzco)
library(ollamar)
library(dplyr)

llm_results <- llm_image_classification(llm_model = "llava-phi3", image = "inst/img/test_img.jpg")
```

Error:

`
Fehler in file(con, "r") : kann Verbindung nicht öffnen
Zusätzlich: Warnmeldung:
In file(con, "r") :
  kann Datei 'inst/prompts/system-prompt.md' nicht öffnen: No such file or directory
`

From what I figured out, this seems to be due to the way the paths to the prompt .md files are specified in the `llm_image_classification()` function.

I was able to fix it by changing the function code to this:

```
llm_image_classification <- function(llm_model = "llava-phi3", image = "inst/img/test_img.jpg") 
{
  system_prompt <- paste(base::readLines(paste0(.libPaths()[1],
                                                "/kuzco/prompts/system-prompt.md")), 
                         collapse = "\n")
  image_prompt <- paste(base::readLines(paste0(.libPaths()[1],
                                               "/kuzco/prompts/image-prompt.md")), 
                        collapse = "\n")
  llm_json <- ollamar::generate(model = llm_model, prompt = image_prompt, 
                                images = image, system = system_prompt, output = "text")
  llm_parsed <- jsonlite::parse_json(llm_json)
  llm_df <- dplyr::select(as.data.frame(llm_parsed), image_classification:image_colors)
  image_proba_nms <- llm_parsed$image_proba_names
  image_proba_val <- llm_parsed$image_proba_values
  llm_df <- dplyr::mutate(llm_df, image_proba_names = list(image_proba_nms), 
                          image_proba_values = list(image_proba_val))
  return(llm_df)
}
```

**Comment by frankiethull** [comment]
thank you for your feedback, testing, and providing a fix.

I can make this change in the next day or two. If you'd like to be added as contributor feel free to PR and I will accept this solution once I test. :)

**Comment by frankiethull** [comment]
https://github.com/frankiethull/kuzco/pull/3 closes this.

@jobreu let me know if you have any other ideas, suggestions, or improvements you can think of. Adding you as contributor shortly.
